spring:
  application:
    name: zuul-ext
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuulext
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: 10000
  data:
    redis:
      repositories:
        enabled: false
zuul:
  ratelimit:
    enabled: true
    repository: redis
eureka:
  client:
    enabled: false