spring:
  application:
    name: zuul-ext
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuulext
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true



zuul-ext:
  redisEnable: false